Bugfix for ConfiguredObjectProvenance and StructuralEquals on ConfigurationData
oracle/olcut pull request #36
Opened 2021-08-30 13:31 UTC by JackSullivan

## Bugfix

Provenance instances for implementations that depend on `SkeletalConfiguredObjectProvenance` populate an empty string rather than nothing for null-valued string fields that are annotated with `@Config`. This fixes that issue. The issue was discovered because it was causing `ConfigurationData` instances produced through the provenance system to not match those produced through importing a configurable object into `ConfigurationManager`. There may be instances of incorrect provenances in the wild that this affects, but I suspect the chances are fairly small.

## Enhancement

Added a method to check whether two configured objects are structurally equal to one another by checking whether their types and property values match, dereferencing property values that correspond to the names of other configured objects and recursively equality checking them.

2021-08-30 14:34 UTC, Craigacp requested changes
Could you also add a test where the equals is true and one where it's false? You should be able to generate objects which round trip through provenance using the existing provenance test utils and then compare to see if they are equal.

2021-08-30 14:34 UTC, Craigacp commented on olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationData.java
> +     * <p></p>
Can you remove the `</p>` close tag?

2021-08-30 14:34 UTC, Craigacp commented on olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationData.java
> +     *
Might be useful to note that this method is extremely chatty at the info level in the Javadoc when it finds discrepancies. Most other things in OLCUT tend to log at fine unless it's an actual issue, and that might be appropriate here.

2021-08-30 14:34 UTC, Craigacp commented on olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationData.java
> +                                                logger.info(String.format("Property key: %s, PropValue Key: %s, a.value: %s, b.value: %s",
Doesn't `simplePropertyDerefEquals` already log this? If so, then this lambda can drop the return statement and it'll be much nicer.

2021-08-30 14:34 UTC, Craigacp commented on olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationData.java
> +                        Optional<Property> aPropOpt = Optional.ofNullable(aRoot.getProperties().get(propName));
Can we extract this lambda into a static method? It's hard to figure out what it's capturing and that level of complexity in a lambda body worries me (e.g. it's harder to debug). If possible could you recursively do that so the nested lambdas are also static methods? There are too many return statements for too many functions.

2021-08-31 16:28 UTC, JackSullivan commented
I believe I've addressed all of the changes addressed above. In the process I removed the tests that used `Random` fields throughout, since they are both deprecated and incompatible with provenance.

2021-09-02 20:12 UTC, JackSullivan commented on olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationData.java
> +            } else {
Add a clause to account for mismatched property types

2021-09-13 16:26 UTC, Craigacp requested changes
A bunch of small things, mostly formatting and docs.

2021-09-13 16:26 UTC, Craigacp commented on olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationData.java
> +                if(!listMatch) {
This line doesn't seem to be indented properly.

2021-09-13 16:26 UTC, Craigacp commented on olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationData.java
> +                            logger.fine("bags not equal:\na: " + as.toString() +  "\nb: " + bs.toString());
I think this should be `ListProperties not equal`, or `ListProperties not equal using bag equality`. I see there's more logging further down, but I think being specific here and in the class one will make it a little easier to see.

2021-09-13 16:26 UTC, Craigacp commented on olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationData.java
> +        @Override public int hashCode() {
We have override on the line before the method declaration.

2021-09-13 16:26 UTC, Craigacp commented on olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationData.java
> +     * equal recursively.
Add a note saying it does not compare the serializedForm, importable, exportable, leaseTime or entries attributes of the configuration data. Everything apart from serializedForm is going to go away in the next version anyway, but it's worth noting here.

2021-09-13 16:26 UTC, Craigacp commented on olcut-core/src/main/java/com/oracle/labs/mlrg/olcut/config/ConfigurationData.java
> +     * At log-level {@code FINE} this reports the first place where the two instances differ, and the nature of their
Maybe expand this slightly? It logs all the places where the two instances differ in whatever object they differ in. Possibly `reports the first object where the two instances differ`, but that's not particularly clear either.

2021-09-13 16:26 UTC, Craigacp commented on olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/config/ConfigurationDataTest.java
> +package com.oracle.labs.mlrg.olcut.config;
This file needs a copyright & license header.

2021-09-13 16:26 UTC, Craigacp commented on olcut-core/src/test/java/com/oracle/labs/mlrg/olcut/config/ConfigurationDataTest.java
> +        ch.setLevel(Level.FINE);
Can you back out the logging changes from this test?

2021-09-13 18:04 UTC, Craigacp approved these changes
LGTM

2021-09-13 18:04 UTC, merged